In [6]:
import pandas as pd
df =pd.read_csv("C:\\Pratheeksha SJU\\6th Semester\\Machine Learning\\Life Expectancy Data.csv")
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [50]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [9]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [10]:
#df['Life expectancy'] = df['Life expectancy'].fillna(df['Life expectancy'].mean())
#df['Adult Mortality'] = df['Adult Mortality'].fillna(df['Adult Mortality'].mean())
df_new = df.fillna(df.mean(numeric_only = True))
df_new

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [11]:
df_new.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

In [12]:
corr_df = df_new.corr(numeric_only = True)
corr_df

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
Year,1.000000,0.169623,-0.078861,-0.037415,-0.048168,0.031400,0.089398,-0.082493,0.108327,-0.042937,0.093820,0.081860,0.133853,-0.139741,0.093351,0.014951,-0.047592,-0.050627,0.236333,0.203471
Life expectancy,0.169623,1.000000,-0.696359,-0.196535,0.391598,0.381791,0.203771,-0.157574,0.559255,-0.222503,0.461574,0.207981,0.475418,-0.556457,0.430493,-0.019638,-0.472162,-0.466629,0.692483,0.715066
Adult Mortality,-0.078861,-0.696359,1.000000,0.078747,-0.190408,-0.242814,-0.138591,0.031174,-0.381449,0.094135,-0.272694,-0.110875,-0.273014,0.523727,-0.277053,-0.012501,0.299863,0.305366,-0.440062,-0.435108
infant deaths,-0.037415,-0.196535,0.078747,1.000000,-0.113812,-0.085612,-0.178783,0.501128,-0.227220,0.996629,-0.170674,-0.126564,-0.175156,0.025231,-0.107109,0.548522,0.465590,0.471228,-0.143663,-0.191757
Alcohol,-0.048168,0.391598,-0.190408,-0.113812,1.000000,0.339634,0.075447,-0.051055,0.318070,-0.110777,0.213744,0.294898,0.215242,-0.048650,0.318591,-0.030765,-0.416946,-0.405881,0.416099,0.497546
percentage expenditure,0.031400,0.381791,-0.242814,-0.085612,0.339634,1.000000,0.011679,-0.056596,0.228537,-0.087852,0.147203,0.173414,0.143570,-0.097857,0.888140,-0.024648,-0.251190,-0.252725,0.380374,0.388105
Hepatitis B,0.089398,0.203771,-0.138591,-0.178783,0.075447,0.011679,1.000000,-0.090317,0.134929,-0.184413,0.408519,0.050084,0.499958,-0.102405,0.062318,-0.109811,-0.105144,-0.108334,0.150992,0.171755
Measles,-0.082493,-0.157574,0.031174,0.501128,-0.051055,-0.056596,-0.090317,1.000000,-0.175925,0.507809,-0.136146,-0.104569,-0.141861,0.030899,-0.068060,0.236250,0.224742,0.221007,-0.115764,-0.122609
BMI,0.108327,0.559255,-0.381449,-0.227220,0.318070,0.228537,0.134929,-0.175925,1.000000,-0.237586,0.282156,0.231814,0.281059,-0.243548,0.276645,-0.063238,-0.532025,-0.538911,0.479837,0.508105
under-five deaths,-0.042937,-0.222503,0.094135,0.996629,-0.110777,-0.087852,-0.184413,0.507809,-0.237586,1.000000,-0.188703,-0.128269,-0.195651,0.038062,-0.110640,0.535864,0.467626,0.472099,-0.161533,-0.207111
Polio,0.093820,0.461574,-0.272694,-0.170674,0.213744,0.147203,0.408519,-0.136146,0.282156,-0.188703,1.000000,0.130129,0.673553,-0.159489,0.193980,-0.034882,-0.219938,-0.220710,0.355398,0.385832
Total expenditure,0.081860,0.207981,-0.110875,-0.126564,0.294898,0.173414,0.050084,-0.104569,0.231814,-0.128269,0.130129,1.000000,0.145597,-0.001383,0.121467,-0.066698,-0.268724,-0.275240,0.149095,0.218310
Diphtheria,0.133853,0.475418,-0.273014,-0.175156,0.215242,0.143570,0.499958,-0.141861,0.281059,-0.195651,0.673553,0.145597,1.000000,-0.164787,0.182795,-0.025458,-0.227820,-0.221105,0.371729,0.389944
HIV/AIDS,-0.139741,-0.556457,0.523727,0.025231,-0.048650,-0.097857,-0.102405,0.030899,-0.243548,0.038062,-0.159489,-0.001383,-0.164787,1.000000,-0.134514,-0.027318,0.203922,0.207140,-0.247454,-0.218620
GDP,0.093351,0.430493,-0.277053,-0.107109,0.318591,0.888140,0.062318,-0.068060,0.276645,-0.110640,0.193980,0.121467,0.182795,-0.134514,1.000000,-0.025612,-0.267745,-0.272400,0.440317,0.429489
Population,0.014951,-0.019638,-0.012501,0.548522,-0.030765,-0.024648,-0.109811,0.236250,-0.063238,0.535864,-0.034882,-0.066698,-0.025458,-0.027318,-0.025612,1.000000,0.236117,0.233941,-0.007951,-0.029465
thinness 1-19 years,-0.047592,-0.472162,0.299863,0.465590,-0.416946,-0.251190,-0.105144,0.224742,-0.532025,0.467626,-0.219938,-0.268724,-0.227820,0.203922,-0.267745,0.236117,1.000000,0.939102,-0.406662,-0.446140
thinness 5-9 years,-0.050627,-0.466629,0.305366,0.471228,-0.405881,-0.252725,-0.108334,0.221007,-0.538911,0.472099,-0.220710,-0.275240,-0.221105,0.207140,-0.272400,0.233941,0.939102,1.000000,-0.395779,-0.435777
Income composition of resources,0.236333,0.692483,-0.440062,-0.143663,0.416099,0.380374,0.150992,-0.115764,0.479837,-0.161533,0.355398,0.149095,0.371729,-0.247454,0.440317,-0.007951,-0.406662,-0.395779,1.000000,0.796207
Schooling,0.203471,0.715066,-0.435108,-0.191757,0.497546,0.388105,0.171755,-0.122609,0.508105,-0.207111,0.385832,0.218310,0.389944,-0.218620,0.429489,-0.029465,-0.446140,-0.435777,0.796207,1.000000

In [13]:
df_new.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [14]:
df_new.columns = df_new.columns.str.strip()

In [15]:
df_new.columns = (
    df_new.columns
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

clean_df = df_new.drop(
    ['Adult Mortality', 'infant deaths', 'Measles',
     'under-five deaths', 'HIV/AIDS', 'Population',
     'thinness 1-19 years', 'thinness 5-9 years'],
    axis=1
)

clean_df

,Country,Year,Status,Life expectancy,Alcohol,percentage expenditure,Hepatitis B,BMI,Polio,Total expenditure,Diphtheria,GDP,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,0.01,71.279624,65.0,19.1,6.0,8.16,65.0,584.259210,0.479,10.1
1,Afghanistan,2014,Developing,59.9,0.01,73.523582,62.0,18.6,58.0,8.18,62.0,612.696514,0.476,10.0
2,Afghanistan,2013,Developing,59.9,0.01,73.219243,64.0,18.1,62.0,8.13,64.0,631.744976,0.470,9.9
3,Afghanistan,2012,Developing,59.5,0.01,78.184215,67.0,17.6,67.0,8.52,67.0,669.959000,0.463,9.8
4,Afghanistan,2011,Developing,59.2,0.01,7.097109,68.0,17.2,68.0,7.87,68.0,63.537231,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,4.36,0.000000,68.0,27.1,67.0,7.13,65.0,454.366654,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,4.06,0.000000,7.0,26.7,7.0,6.52,68.0,453.351155,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,4.43,0.000000,73.0,26.3,73.0,6.53,71.0,57.348340,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,1.72,0.000000,76.0,25.9,76.0,6.16,75.0,548.587312,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,1.68,0.000000,79.0,25.5,78.0,7.10,78.0,547.358878,0.434,9.8

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [17]:
y = clean_df['Life expectancy']
x = clean_df.drop(['Life expectancy'], axis = 1)
x = pd.get_dummies(x, drop_first = True)

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 10)

In [18]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred = model.predict(x_test)
#y_pred

In [20]:
#Evaluation
r2 = r2_score(y_test, y_pred)
print('R2 Score:', r2)

R2 Score: 0.9448222253999534

In [21]:
#How much error is there in predicted
mse = mean_squared_error(y_test,y_pred)
print('Mean Squared Error: ',mse)

Mean Squared Error:  4.930757227349847

In [22]:
#!pip install xgboost
#XGBoost Regression for the same dataset
from xgboost import XGBRegressor

xbr_model = XGBRegressor()

In [23]:
xbr_model.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [24]:
y_pred_xbr = xbr_model.predict(x_test)
#y_pred_xbr

In [25]:
r2_xbr = r2_score(y_test,y_pred_xbr)
print("XGBoost R2 = ", r2_xbr)

XGBoost R2 =  0.9449681841159435

Linear Regression was used as a baseline model to understand the relationship between health and socio-economic factors and life expectancy, but its performance was limited due to linear assumptions. XGBoost Regressor performed better by capturing non-linear relationships and complex feature interactions, resulting in higher prediction accuracy and lower error values.